Repository Okura-JCH/Okura, pull requests merged in 2024-03, with the labels that each got.

#12 Add workflow to add issues and pull requests to Kanban project
  .github/workflows/add-to-kanban-project.yml
Labels: enhancement

#11 Add workflow to assign PR creator
  .github/workflows/assign-creator.yml
Labels: enhancement

#13 Add Dependabot configuration file
  .github/dependabot.yml
Labels: enhancement

#21 Navigation route impl
  app/build.gradle.kts
  app/src/main/java/com/example/okura/AppNavigation.kt
  app/src/main/java/com/example/okura/MainActivity.kt
  app/src/main/java/com/example/okura/presentation/view/SearchArticleScreen.kt
Labels: enhancement

#24 Screens initial setup
  app/src/main/java/com/example/okura/AppNavigation.kt
  app/src/main/java/com/example/okura/MainActivity.kt
  app/src/main/java/com/example/okura/presentation/view/HomeScreen.kt
  app/src/main/java/com/example/okura/presentation/view/PeopleScreen.kt
  app/src/main/java/com/example/okura/presentation/view/ProfileScreen.kt
Labels: enhancement

#29 Transparent HomeAppBar
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/okura/MainActivity.kt
  app/src/main/java/com/example/okura/presentation/view/HomeScreen.kt
Labels: enhancement

#23 Add Android CI workflow
  .github/workflows/android_build.yml
Labels: enhancement

#30 Bottom navbar UI impl
  app/src/main/java/com/example/okura/ui/components/HomeNavBar.kt
Labels: enhancement

#32 もれてたやつ・・・入れてください・・・(´;ω;`)ﾌﾞﾜｯ
  .idea/deploymentTargetDropDown.xml
Labels: enhancement

#37 [impl] Horizontal pager (carousels)
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/java/com/example/okura/presentation/view/HomeScreen.kt
  app/src/main/java/com/example/okura/ui/components/carousel/Carousel.kt
  app/src/main/java/com/example/okura/ui/components/carousel/CarouselCard.kt
  app/src/main/java/com/example/okura/ui/components/carousel/CarouselDescription.kt
  app/src/main/java/com/example/okura/ui/components/carousel/DotIndicator.kt
  app/src/main/res/drawable/sample.png
  build.gradle.kts
Labels: enhancement

#43 Fix Lint Error
  app/build.gradle.kts
  app/src/androidTest/java/com/example/okura/ExampleInstrumentedTest.kt
  app/src/main/java/com/example/okura/MainActivity.kt
  app/src/main/java/com/example/okura/presentation/components/HomeNavBar.kt
  app/src/main/java/com/example/okura/presentation/components/carousel/Carousel.kt
  app/src/main/java/com/example/okura/presentation/components/carousel/CarouselCard.kt
  app/src/main/java/com/example/okura/presentation/components/carousel/CarouselDescription.kt
  app/src/main/java/com/example/okura/presentation/components/carousel/DotIndicator.kt
  app/src/main/java/com/example/okura/presentation/view/screens/HomeScreen.kt
  app/src/main/java/com/example/okura/presentation/view/screens/PeopleScreen.kt
  app/src/main/java/com/example/okura/presentation/view/screens/ProfileScreen.kt
  app/src/main/java/com/example/okura/presentation/view/screens/SearchArticleScreen.kt
  app/src/main/java/com/example/okura/ui/theme/Color.kt
  app/src/main/java/com/example/okura/ui/theme/Theme.kt
  app/src/main/java/com/example/okura/ui/theme/Type.kt
  app/src/test/java/com/example/okura/ExampleUnitTest.kt
Labels: bug

#41 Add .gitignore entry for Copilot chat sessions
  .idea/.gitignore
Labels: bug

#45 Update Gradle build command and add artifact upload step to Android build workflow
  .github/workflows/android_build.yml
Labels: enhancement

#44 [impl]News feed
  .idea/deploymentTargetDropDown.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/okura/domain/data/NewsRepository.kt
  app/src/main/java/com/example/okura/domain/data/SampleNewsData.kt
  app/src/main/java/com/example/okura/domain/model/NewsItem.kt
  app/src/main/java/com/example/okura/presentation/components/carousel/Carousel.kt
  app/src/main/java/com/example/okura/presentation/components/feed/NewsCard.kt
  app/src/main/java/com/example/okura/presentation/components/feed/NewsFeed.kt
  app/src/main/java/com/example/okura/presentation/view/screens/HomeScreen.kt
Labels: enhancement

#56 ちょっとダケ読みやすく👀しちゃったヨ😁‼️
  app/src/main/java/com/example/okura/presentation/components/HomeAppBar.kt
  app/src/main/java/com/example/okura/presentation/components/NavigationBarItems.kt
  app/src/main/java/com/example/okura/presentation/view/screens/HomeScreen.kt
Labels: enhancement

#34 Add CodeQL workflow
  .github/workflows/codeql.yml
Labels: bug

#59 Setup CategoryCard
  app/src/main/java/com/example/okura/domain/data/NewsRepository.kt
  app/src/main/java/com/example/okura/domain/data/SampleNewsData.kt
  app/src/main/java/com/example/okura/domain/model/NewsCategory.kt
  app/src/main/java/com/example/okura/domain/model/NewsItem.kt
  app/src/main/java/com/example/okura/presentation/components/CategoryCard.kt
  app/src/main/java/com/example/okura/presentation/components/CategoryGrid.kt
  app/src/main/java/com/example/okura/presentation/components/bars/HomeAppBar.kt
  app/src/main/java/com/example/okura/presentation/components/bars/HomeNavBar.kt
  app/src/main/java/com/example/okura/presentation/components/bars/NavigationBarItems.kt
  app/src/main/java/com/example/okura/presentation/components/feed/NewsCard.kt
  app/src/main/java/com/example/okura/presentation/view/screens/HomeScreen.kt
  app/src/main/java/com/example/okura/presentation/view/screens/PeopleScreen.kt
Labels: enhancement

#58 Add DevContainer
  .devcontainer/Dockerfile
  .devcontainer/android-sdk-licenses/android-googletv-license
  .devcontainer/android-sdk-licenses/android-sdk-arm-dbt-license
  .devcontainer/android-sdk-licenses/android-sdk-license
  .devcontainer/android-sdk-licenses/android-sdk-preview-license
  .devcontainer/android-sdk-licenses/google-gdk-license
  .devcontainer/android-sdk-licenses/mips-android-sysimage-license
  .devcontainer/devcontainer.json
  .github/dependabot.yml
  .github/workflows/devcontainer-build.yml
  .github/workflows/docker-lint.yml
Labels: enhancement

#66 SearchArticleScreenのUI作ったヨ❗️😁👌
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/okura/MainActivity.kt
  app/src/main/java/com/example/okura/domain/data/api/NewsApiService.kt
  app/src/main/java/com/example/okura/domain/data/api/RetrofitInstance.kt
  app/src/main/java/com/example/okura/domain/data/repository/NewsRepository.kt
  app/src/main/java/com/example/okura/domain/data/repository/SampleNewsData.kt
  app/src/main/java/com/example/okura/presentation/NewsViewModelFactory.kt
  app/src/main/java/com/example/okura/presentation/components/articles/CategoryCard.kt
  app/src/main/java/com/example/okura/presentation/components/articles/CategoryGrid.kt
  app/src/main/java/com/example/okura/presentation/components/feed/NewsFeed.kt
  app/src/main/java/com/example/okura/presentation/view/screens/HomeScreen.kt
  app/src/main/java/com/example/okura/presentation/view/screens/PeopleScreen.kt
  app/src/main/java/com/example/okura/presentation/view/screens/SearchArticleScreen.kt
  app/src/main/java/com/example/okura/presentation/viewmodel/NewsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: enhancement

#69 Add detailed README for Okura project
  README.md
Labels: enhancement, dependencies
